### ISSUE TITLE
scroll bug

### ISSUE THREAD

**Issue by WJer** [chameleon-team/chameleon-ui-builtin#4]
现象：
通过scroller的onscroll事件获取scrollLeft值。组件在手释放后由于惯性会继续滚动，例如会继续滚动到100px的偏移量（假设的值）。如果在这个过程中，用手指停止其惯性滚动（<100px）。onscroll获取的scrollLeft任是100px，并不是实际滚动的举例。

**Comment by beatles-chameleon** [comment]
请描述下是哪一端，cli版本，项目package.json

**Comment by WJer** [comment]
是在h5上测试的。chameleon-ui-builtin@0.2.10-alpha.4

**Comment by WJer** [comment]
onscroll事件，滚动条还没停止，onscroll事件处理函数里的参数便已经获取到了滚动条停止后的scrolltop

**Comment by WJer** [comment]
> 请描述下是哪一端，cli版本，项目package.json

是在h5上测试的。chameleon-ui-builtin@0.2.10-alpha.4

**Comment by huyuangang** [comment]
使用chameleon-ui-builtin@0.2.11-alpha.2之后的版本试一下
